<h1><b>Introduction to <span style ="color:#306998">Num</span><span style ="color: #FFD43B">Py</span></b></h1>
<h3><b>Day1->Practice and Notes</b></h3>

<p><b>1. Numpy first program:
        ->Creating a simple 1D & 2D Array</b></p>
        <sub>1D array -> Vector</sub><br>
        <sub>2D array -> Matrix</sub>

In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
np.array([[1,2,3,3],[10,20,30,40]])

array([[ 1,  2,  3,  3],
       [10, 20, 30, 40]])

<p><b>2. Creating 1D and 2D arrays having all elements 0</b></p>

<span style="color: pink">>>1D</span>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

<span style="color: pink">>>2D</span>

<sub><span style="color: pink">>>No any variable are assigned here, so it is temporarily stored in system's memory and later thrown away as garbage after finishing execution</span></sub>

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<span style="color: pink">>>3D</span><br>
<sub>(2,3,4)</sub><br>
<sub>2-->blocks(matrices)</sub><br>
<sub>3-->rows in each block</sub><br>
<sub>4-->columns in each row</sub>

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

<sub><span style="color: pink">>>Assigning a variable to an array helps to store safely in memory</span></sub>

In [6]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<p><b>3. Array Attributes in NumPy</b></p>
<sub><span style="color: pink">~.shape: returns size of array in tuple and tells exact layout of the data</span></sub>

In [7]:
a.shape

(3, 4)

<sub><span style="color: pink">~.ndim: returns the no. of dimension of your dataset</span></sub>

In [8]:
a.ndim

2

<sub><span style="color: pink">~.size: returns total no. of elements inside  the array</span></sub>

In [9]:
a.size

12

<p><b>4. Creating 3x4 matrix of each element 1</b></p>

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<p><b>5. Creating 3x4 matrix of each element having value of PI</b></p>

In [11]:
np.full((3,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

<p><b>6. Creating 3x4 matix having all element 2</b></p>

In [12]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

<p><b>7. Arange->.arange(start, stop, step)</b></p>
<sub><span style="color: pink">~Generates values within a half-open interval(i.e upto n-1 place)</span></sub><br>

<sub><span style="color:green">start</span> : Beginning of the interval (default is `0`).<br>
     <span style="color:green">stop</span> : End of the interval (exclusive).<br>
     <span style="color:green">step</span> : Spacing between values (default is `1`).</sub><br>


In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [14]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

<p><b>7. Linspace->.linspace(start, stop, num)</b></p>
<sub><span style="color: pink">~Generates values within a half-open interval(i.e upto n-1 place)</span></sub><br>

<sub><span style="color:green">start</span> : Beginning of the interval.<br>
     <span style="color:green">stop</span> : End of the interval (inclusive by default).<br>
     <span style="color:green">num</span> : Number of samples to generate.</sub><br>


In [15]:
print(np.linspace(0,5/3,6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [16]:
print(np.arange(0,5/3,0.333333333))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [17]:
print(np.arange(0,5/3,0.333333334))

[0.         0.33333333 0.66666667 1.         1.33333334]


<p><b>8. Random Numbers Generation: rand & randn</b></p>
<sub><span style="color: pink">>>.rand(rows, cols): Generates random decimals strictly between 0 and 1.<br>
            ~Uniform distribution-> even chance for every num<br>
            ~Only +ve numbers</span></sub>

In [18]:
np.random.rand(3,4)

array([[0.92660902, 0.89811441, 0.3304295 , 0.2195123 ],
       [0.93054926, 0.24170751, 0.51664095, 0.5518136 ],
       [0.2859075 , 0.67632218, 0.59204593, 0.70735959]])

<sub><span style="color: pink">>>.rand(rows, cols): Generates random numbers centered around 0<br>
            ~Normal distribution-> most numbers cluster close to 0<br>
            ~Both +ve  & -ve numbers</span></sub>

In [19]:
np.random.randn(3,4)

array([[-0.77462663, -0.18281523,  2.48208978,  0.60274603],
       [-1.46223058, -1.51000713,  1.79713305, -3.00489168],
       [-1.50896004, -1.7557003 , -0.84199814,  0.0936899 ]])

<p><b>9. Specifying DataType and Checking Memory</b></p>
<sub><span style="color: pink">~dtype: Forcing a specific datatype(complex, float)</span></sub><br>

In [20]:
d=np.arange(1,5,dtype=np.complex64)
print(d.dtype,d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


<sub><span style="color: pink">~.itemsize: returns how many bytes a single element in your array takes up in memory.</span></sub><br>

In [21]:
e=np.arange(1,5,dtype=np.complex64)
e.itemsize

8

In [22]:
e=np.arange(1,5,dtype=np.float32)
e.itemsize

4

In [23]:
d=np.arange(1,5,dtype=np.float32)
print(d.dtype,d)

float32 [1. 2. 3. 4.]


<p><b>10. Use of reshape</b></p>
<sub><span style="color: pink">First creating a simple list of numbers from 0 to 23</span></sub><br>


In [24]:
g=np.arange(24)
print(g)
print("rank:",g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
rank: 1


<sub><span style="color: pink">Then changing dimension of array without changing actual data elements</span></sub>

In [25]:
g2=g.reshape(4,6)
print(g2)
print("rank:",g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
rank: 2


<sub><span style="color: pink">Creating another 2x2 list </span></sub>

In [26]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


<sub><span style="color: pink">.reshape(1, 4): Flattens those 4 elements into a single horizontal row containing 4 columns.</span></sub>

In [27]:
g3=a.reshape(1,4)
print(g3)
print("rank:",g3.ndim)

[[0. 0. 0. 0.]]
rank: 2


<p><b>11. Updating Elements</b></p>
<sub><span style="color: pink">g2[1,2]: updates the value located in row index 1 and column index 2(i.e 2nd row 3rd column)</span></sub><br>
<sub><span style="color: green">Note : Numpy uses 0-based indexing(staring from 0)</span></sub>

In [28]:
g2[1,2]=999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

<p><b>12. Flattening Arrays: ravel(), flatten() & reshape()</b></p>

<sub><span style="color: pink">Used to collapse multi-dimensional arrays into flat, simple 1D array</span></sub>

<sub><span style="color: green"><b>.ravel()</b>:<br>
points directly to your original data<br>
changes original data too<br>
Very fast and no use of extra memory</span></sub>

In [29]:
a.ravel()

array([0., 0., 0., 0.])

<sub><span style="color: green"><b>.flatten()</b>:<br>
makes a brand-new, independent copy of your data in memory<br>
Changing values here will not affect your original array</span></sub>

In [30]:
a.flatten()

array([0., 0., 0., 0.])

In [31]:
b=np.zeros((100,100))
print(b)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
b=b.ravel()

In [ ]:
b=b.flatten()


<sub><span style="color: green"><b>.reshape(-1)</b>:<br>
automatically flat-pack everthing into 1D array<br>
Like ravel(), this is just a shortcut (view) of the original array, not a copy.</span></sub>

In [34]:
b=b.reshape(-1)

In [35]:
b.shape

(10000,)

<p><b>13. Arithmetic Operators</b></p>
<b><sub><span style="color: pink">+, -, /, *, //, **</span></sub></b>

In [ ]:
a=np.array([14,23,32,41])
b=np.array([5,4,3,2])
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a//b=",a//b)
print("a%b=",a%b)
print("a**b=",a**b)

a+b= [19 27 35 43]
a-b= [ 9 19 29 39]
a*b= [70 92 96 82]
a/b= [ 2.8         5.75       10.66666667 20.5       ]
a//b= [ 2  5 10 20]
a%b= [4 3 2 1]
a**b= [537824 279841  32768   1681]
