<h2>Broadcasting</h2>
#rules of broadcasting|

#First Rule

In [3]:
import numpy as np
h = np.arange(5).reshape(1, 1, 5)


In [4]:
h + [10, 20, 30, 40, 50]

array([[[10, 21, 32, 43, 54]]])

#Second Rule

In [5]:
k = np.arange(6).reshape(2, 3)


In [ ]:
k+[[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

#Third rule


In [8]:
k = np.arange(9).reshape(3, 3)
try:
    k + [33, 44]
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (2,) 


In [14]:
a = np.array([1, 2])
b = np.array([[(1, 2)]])



In [17]:
a.shape


(2,)

In [18]:
b.shape

(1, 1, 2)

#qno1->scale broadcasting

<sub>Creating a numpy array and adding 20 to every element using broadcasting</sub>

In [19]:
a = np.array([5, 10, 15, 20, 25])

In [20]:
a +[10]

array([15, 20, 25, 30, 35])

#qno2_> Row wise broad casting<br>
<sub>Create matrix and using broadcasting, add the row vector [10,20,30] to every row of the matrix</sub>

In [22]:
b = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [23]:
b +[10, 20, 30]

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

#qno.3-> column broadcasting

In [42]:
x = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

In [43]:
res = x + [[1],
           [2],
           [3]]
print(res)

[[11 21 31]
 [42 52 62]
 [73 83 93]]


#qno.4->broadcasting with different dimension


In [30]:
A = np.array([1, 2, 3])
B = np.array([10, 20, 30, 40])

In [31]:
C = A.reshape(3, 1) + B
print(C)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [32]:
answer = A[:,np.newaxis]+B
print(answer)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


#qno.5->real world data processing
<sub>Create the following matrix of four students in three subjects </sub>

In [34]:
arr = np.array([[65, 40, 75],
               [80, 85, 90],
               [55, 60, 65],
               [95, 90, 85]])

In [35]:
arr + [5, 3, 2]

array([[ 70,  43,  77],
       [ 85,  88,  92],
       [ 60,  63,  67],
       [100,  93,  87]])

<h2>Upcasting</h2>
<sub>-when trying to combine arrays with different dtypes, NumPy will upcast to a type capable of handling all possible values</sub>

In [44]:
k1 = np.arange(0, 5, dtype=np.uint8)

In [45]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


#Broadcasting with conditional operators

In [47]:
m = np.array([20, -5, 30, 40])
m[m < 25]

array([20, -5])

#Mathematical and Statistical Functions<br>
<sub>~This performs the operation on all elements in the ndarray, regardless of its shape</sub>

In [48]:
a = np.array([[-.25, 3.1, 7], [10, 11, 12]])

In [50]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var, a.mean):
    print(func,__name__,"=", func())

<built-in method min of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = -0.25
<built-in method max of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = 12.0
<built-in method sum of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = 42.85
<built-in method prod of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = -7161.0
<built-in method std of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = 4.428168984530237
<built-in method var of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = 19.608680555555555
<built-in method mean of numpy.ndarray object at 0x000001E2F07C5E90> __main__ = 7.141666666666667
