Question 3: Indexing a 4D Array

In [1]:
import numpy as np
tensor_box = np.arange(1, 49).reshape(2, 2, 3, 4)

Print the first 3D block

In [2]:
print("1.")
print(tensor_box[0])


1.
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [3]:
print("\n2.")
print(tensor_box[0, 1])


2.
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [4]:
print("\n3.")
print(tensor_box[1, 1, 2])


3.
[45 46 47 48]


In [5]:
print("\n4.")
print(tensor_box[0, :, :, -1])


4.
[[ 4  8 12]
 [16 20 24]]


In [6]:
print("\n5.")
print(tensor_box[1, 1, 2, 3])


5.
48


In [7]:
print("\n6.")
print(tensor_box[1, 0, :, :2])


6.
[[25 26]
 [29 30]
 [33 34]]


Question 4: Advanced Slicing on a 4D Array

In [8]:
matrix_hub = np.arange(1, 97).reshape(2, 3, 4, 4)

In [9]:
print("1.")
print(matrix_hub[1])

1.
[[[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]

 [[65 66 67 68]
  [69 70 71 72]
  [73 74 75 76]
  [77 78 79 80]]

 [[81 82 83 84]
  [85 86 87 88]
  [89 90 91 92]
  [93 94 95 96]]]


In [10]:
print("\n2.")
print(matrix_hub[:, :, :2, :])


2.
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[17 18 19 20]
   [21 22 23 24]]

  [[33 34 35 36]
   [37 38 39 40]]]


 [[[49 50 51 52]
   [53 54 55 56]]

  [[65 66 67 68]
   [69 70 71 72]]

  [[81 82 83 84]
   [85 86 87 88]]]]


In [11]:
print("\n3.")
print(matrix_hub[:, :, :, 2:])



3.
[[[[ 3  4]
   [ 7  8]
   [11 12]
   [15 16]]

  [[19 20]
   [23 24]
   [27 28]
   [31 32]]

  [[35 36]
   [39 40]
   [43 44]
   [47 48]]]


 [[[51 52]
   [55 56]
   [59 60]
   [63 64]]

  [[67 68]
   [71 72]
   [75 76]
   [79 80]]

  [[83 84]
   [87 88]
   [91 92]
   [95 96]]]]


In [12]:
print("\n4.")
print(matrix_hub[:, :, ::2, :])


4.
[[[[ 1  2  3  4]
   [ 9 10 11 12]]

  [[17 18 19 20]
   [25 26 27 28]]

  [[33 34 35 36]
   [41 42 43 44]]]


 [[[49 50 51 52]
   [57 58 59 60]]

  [[65 66 67 68]
   [73 74 75 76]]

  [[81 82 83 84]
   [89 90 91 92]]]]


In [13]:
print("\n5.")
print(matrix_hub[:, :, 1:3, 1:3])


5.
[[[[ 6  7]
   [10 11]]

  [[22 23]
   [26 27]]

  [[38 39]
   [42 43]]]


 [[[54 55]
   [58 59]]

  [[70 71]
   [74 75]]

  [[86 87]
   [90 91]]]]


Question 5: Mixed Indexing Challenge (4D)

In [14]:
vault4d = np.arange(1, 121).reshape(2, 3, 4, 5)